image: Visual Studio 2019

platform: x64

configuration: Release

version: ci.{build}

build:
  parallel: true
  project: QuantLib.sln
  verbosity: normal

before_build:
  - COPY .appveyor\userconfig2019.hpp .\ql\userconfig.hpp
  - COPY .appveyor\VS2019.props .\Build.props
  - COPY .appveyor\testsuite.props .\test-suite\Build.props
  - COPY .appveyor\Unity.props .\Directory.Build.props

test_script:
  - .\test-suite\bin\QuantLib-test-suite.exe --log_level=message --build_info=yes -- --faster

